# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GoedDoel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=128)),
                ('bijschrift', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=255)),
                ('foto_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PandReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=128)),
                ('auteur', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=500)),
                ('rating', models.CharField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=5, max_length=2)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=128)),
                ('onderschrift', models.CharField(max_length=255)),
                ('foto_url', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusBericht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('inhoud', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TagPand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pand',
            name='pandtype',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='pand',
        ),
        migrations.AddField(
            model_name='foto',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pand',
            name='beschrijving',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pand',
            name='busnr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pand',
            name='prijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pand',
            name='referentienummer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='pand',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pand',
            name='uitgelicht',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default='a', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 21, 55, 104000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='foto',
            name='pand',
        ),
        migrations.AddField(
            model_name='foto',
            name='pand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Pand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stad',
            name='postcode',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='busnr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PandType',
        ),
        migrations.AddField(
            model_name='tagpand',
            name='pand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Pand'),
        ),
        migrations.AddField(
            model_name='tagpand',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Tag'),
        ),
        migrations.AddField(
            model_name='statusbericht',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
