# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-06 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170807_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandPandDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='panddocument',
            name='pand',
        ),
        migrations.AddField(
            model_name='pandpanddocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.PandDocument'),
        ),
        migrations.AddField(
            model_name='pandpanddocument',
            name='pand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Pand'),
        ),
    ]
