# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160421_1023'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stad',
            managers=[
                ('kanker', django.db.models.manager.Manager()),
            ],
        ),
    ]
