# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160502_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='busnr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
