# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20160421_1148'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stad',
            managers=[
            ],
        ),
    ]
