# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_pand_busnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default=datetime.datetime(2016, 5, 13, 11, 37, 24, 576000, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 11, 37, 34, 435000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stad',
            name='postcode',
            field=models.CharField(max_length=12),
        ),
    ]
