# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160421_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruiker',
            name='busnr',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='postcode',
            field=models.IntegerField(),
        ),
    ]
