# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160513_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='beschrijving',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
