# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160617_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=128)),
                ('waarde', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='tagpand',
            name='pand',
        ),
        migrations.RemoveField(
            model_name='tagpand',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pand',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='pand',
            name='badkamers',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='pand',
            name='parkeerplaats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pand',
            name='slaapkamers',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pand',
            name='bouwjaar',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='huisnr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagPand',
        ),
        migrations.AddField(
            model_name='panddetail',
            name='pand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Pand'),
        ),
    ]
