# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170321_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pand',
            name='bouwjaar',
        ),
        migrations.RemoveField(
            model_name='pand',
            name='oppervlakte',
        ),
    ]
