# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20160421_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruiker',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Stad'),
        ),
    ]
