# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_pand_beschrijving'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='referentienummer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
