# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_pand_referentienummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pand',
            name='referentienummer',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
