# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20160421_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gebruiker',
            name='toegangslevel',
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
