# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20160520_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pand',
            name='referentienummer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
