# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20160520_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=2500)),
            ],
        ),
        migrations.RemoveField(
            model_name='pand',
            name='pandtype',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='pand',
        ),
        migrations.AddField(
            model_name='foto',
            name='pand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Pand'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PandType',
        ),
    ]
