# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_panddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='plattegrond',
            field=models.FileField(blank=True, null=True, upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
