# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20160523_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Pand')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='pand',
        ),
        migrations.AddField(
            model_name='tagpand',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Tag'),
        ),
    ]
