# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20160523_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=128)),
                ('onderschrift', models.CharField(max_length=128)),
                ('foto_url', models.CharField(max_length=255)),
            ],
        ),
    ]
