# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='prijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pand',
            name='uitgelicht',
            field=models.BooleanField(default=False),
        ),
    ]
