# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20170401_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plaats',
            field=models.CharField(default='Lier', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=50),
        ),
    ]
