# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20160530_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
