# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_foto_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pand',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
