# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-09 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20170407_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PandReview',
        ),
    ]
