# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_pand_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoedDoel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=255)),
                ('foto_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='onderschrift',
            field=models.CharField(max_length=255),
        ),
    ]
