# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_blijfopdehoogteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blijfopdehoogteuser',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='blijfopdehoogteuser',
            name='min_price',
        ),
        migrations.AddField(
            model_name='blijfopdehoogteuser',
            name='max_prijs',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='blijfopdehoogteuser',
            name='min_prijs',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
