# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20160531_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='goeddoel',
            name='bijschrift',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
