# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_goeddoel_bijschrift'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=128)),
                ('auteur', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=500)),
                ('rating', models.CharField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=5, max_length=2)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
