# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_goeddoel_bijschrift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
    ]
