# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20170411_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blijfopdehoogteuser',
            name='max_prijs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='blijfopdehoogteuser',
            name='min_prijs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pand',
            name='prijs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
