# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20170411_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pand',
            name='postcodeID',
        ),
        migrations.AddField(
            model_name='pand',
            name='plaats',
            field=models.CharField(default='lolol', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pand',
            name='postcode',
            field=models.CharField(default=2600, max_length=50),
            preserve_default=False,
        ),
    ]
