# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_pandreview'),
        ('webapp', '0018_data'),
    ]

    operations = [
    ]
