# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.TextField(),
        ),
    ]
