# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_pand_beschrijving_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pand',
            name='plattegrond',
        ),
        migrations.AddField(
            model_name='panddocument',
            name='plam',
            field=models.BooleanField(default=False),
        ),
    ]
