# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20170411_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panddocument',
            old_name='plam',
            new_name='plan',
        ),
    ]
