# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20160603_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
