# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20170411_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pand',
            name='referentienummer',
            field=models.CharField(default=webapp.models.get_referentienummer, editable=False, max_length=10, unique=True),
        ),
    ]
