# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20170411_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blijfopdehoogteuser',
            name='min_prijs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='blijfopdehoogteuser',
            name='telefoonnummer',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='panddetail',
            name='waarde',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
